# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Area_construida
                                 A QGIS plugin
 Filtra imóveis segundo parametros de área construida
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-21
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Mauro Alixandrini
        email                : mauro.alixandrini@ufba.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import *

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .area_construida_dialog import Area_construidaDialog
import os.path
import processing
import sys, os
from osgeo import ogr

class Area_construida:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Area_construida_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&SEFAZ')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Area_construida', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/area_construida/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Área construida'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Área construida'),
                action)
            self.iface.removeToolBarIcon(action)
### Inserção de novas funções para conecção com GUI
    def loadVector(self):
        """ Load vector layes from the project to combobox """
        self.dlg.comboBox.clear()
        list_layers = (layer for layer in QgsProject.instance().mapLayers().values())
        list_layers_vector = []
        for layer in list_layers:
            if layer.type() == QgsMapLayer.VectorLayer:
                list_layers_vector.append(layer.name())
        self.dlg.comboBox.addItems(list_layers_vector)
    
    def openVector(self):
        """ load a window for open a layer to the project"""
        open_layer = str(QFileDialog.getOpenFileName(caption="Escolha um arquivo vetorial ...", 
                                                     filter="Shapefiles (*.shp)") [0])
        if (open_layer != ""):
            self.iface.addVectorLayer(open_layer, str.split(os.path.basename(open_layer),".") [0], "ogr")
            self.loadVector()

    def layer1(self):
        layer = None
        layer_name=self.dlg.comboBox.currentText()
        for lyr in QgsProject.instance().mapLayers().values():
            if lyr.name() == layer_name:
                layer = lyr
                break
        return layer

    def variaveis(self):
        self.camada = self.layer1()
        self.area_cosnt=int(self.dlg.lineEdit_2.text())/100
        self.area_min=int(self.dlg.lineEdit_3.text())
        self.saida = self.dlg.lineEdit_4.text()
    
    def output(self):
        output_file, _ = QFileDialog.getSaveFileName(
            caption="Escolha um arquivo vetorial ...",
            filter="Shapefiles (*.shp)"
        )
        if output_file:
            self.dlg.lineEdit_4.setText(output_file)
            self.saida = output_file  # Atualiza a variável de instância

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = Area_construidaDialog()

        # show the dialog
        self.dlg.show()

        # funções adicionadas 
        self.loadVector()
        self.dlg.toolButton.clicked.connect(self.openVector)
        self.dlg.toolButton_2.clicked.connect(self.output)
 
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            # variaveis usadas
            self.variaveis()
            # Execução da tarefa
            lotes = self.camada
            features = []
            for feature in lotes.getFeatures():
                area_terreno = feature['area_terreno']
                area_construida = feature['area_construida']
                if area_construida > (area_terreno * self.area_cosnt) and area_terreno > self.area_min:  # 80% do terreno
                    features.append(feature)
            irregulares = QgsVectorLayer("Polygon?crs=EPSG:31983", "Imóveis Irregulares", "memory")
            irregulares.dataProvider().addFeatures(features)
            #QgsProject.instance().addMapLayer(irregulares)
            # Salva a camada no arquivo de saída
            QgsVectorFileWriter.writeAsVectorFormat(
                irregulares,
                self.saida,  # Usa a variável que contém o caminho
                "UTF-8",
                irregulares.crs(),
                "ESRI Shapefile"
            )

            # Adiciona a camada ao projeto
            if os.path.exists(self.saida):
                self.iface.addVectorLayer(self.saida, "Imóveis Irregulares", "ogr")

            pass
